deploy:
  language: node_js
  node_js:
    - node
  api_key:
    secure: IOmog8FxYmhw/KlqSJjktR4nhYQLzEFNE3mJgj5/p1CH1AjuMJlKUiQINJ6HXWgvlcebUZN/fCF0norILzNMois4u0QC7d+BaO80g+aS13VhAc7ay5auUuU7IC0TC0VRxzbPgKmG4a6DHRUXdiLJODRztjR/Q3FDtUT5KZLL8LCVEANDBwUOGMyQCLlDBeykYHy5/zItbsLjgvMBAwm6iGaSQ9GYNutBuc4QnRAa7D65nf3ZaBXt/4TZD5x7L8V1DmTt2gxA8Q1YxHVME9A/IwXeP0VoB+JYTHUokNm0wjDY1OUNvKL8bN0iE914H/wx4uv1/3TWqopNun6a5vadQVmzVWy9+qGxyhE6Gy5oINqq+5RPbmjBXANV02EsbmC/UPHSuZBmsheRGghuzRdsGJ4c3+rq1qNK+I6FqdNXbkTb0BLeHiNGrie+6cft7I9DWs10F/gd8VlrgMMC1z0ZTzy6PoU0++Oj8yyaIjC6cSQP0KurdXLhpzuKneF5oCi0zgTsgUJ/QF260OM2vqE2mXOUfGaCtjhJ91+4hi9coWPP3zdTX1SdvNmCxdk80jED+lNVwJgUbdGSUsq0rk86Lvqzntm8aZ2uLBlam8WHQpTcXT6FuokkmAzU47n5ic0jmMb9DCk9W8qYswvch/5Zia5+mNQd27Zt2KqFZD6SSL4=
  cache:
    directories:
      - "node_modules"
  branches:
    only:
      - master
      - v1-refactor  